[theme]
primaryColor = "#1E90FF"  # Dodger blue for accents
backgroundColor = "#2E2E2E"  # Dark gray for background
secondaryBackgroundColor = "#3C3C3C"  # Slightly lighter gray for panels
textColor = "#FFFFFF"  # White for text
font = "sans serif"  # Clean and modern font
